#!/usr/bin/env node

const Web3 = require('web3');
const web3 = new Web3(new Web3.providers.HttpProvider('http://localhost:8545'))

web3.eth.isSyncing((error, res) => {
  console.log(error);
  console.log(res);
  if (res === true) {
    console.log("NODE IS CURRENTLY SYNCING");
    web3.reset(true);
  } else if (res) {
    console.log(`Blocks left: ${res.highestBlock - res.currentBlock}`);
  } else {
    console.log("GOOD TO GO!");
  }
});
